services:
  app:
    build:
      context: ./otel-app
      dockerfile: Dockerfile
    command: ["uvicorn", "example_prometheus_alloy:app", "--host", "0.0.0.0", "--port", "5000"]
    ports:
      - "5000:5000"
    depends_on:
      - alloy
    # Nenhuma mudança aqui

  alloy:
    image: grafana/alloy:latest
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy
    command:
      - 'run'
      - '--server.http.listen-addr=0.0.0.0:12345'
      - '--storage.path=/var/lib/alloy/data'
      - '/etc/alloy/config.alloy'
    ports:
      - "4318:4318" # <-- ADICIONE ESTA LINHA!
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-remote-write-receiver'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"