global:
  scrape_interval: 15s # A cada quanto tempo ele busca dados (aqui não será usado, pois o Alloy envia)

scrape_configs:
  # O Prometheus pode se monitorar
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']