version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: n8n_postgres
    environment:
      POSTGRES_USER: n8nuser
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: n8n
    ports:
      - "5432:5432"
    networks:
      - n8n_net

  n8n:
    image: n8nio/n8n
    container_name: n8n_app
    ports:
      - "5678:5678"
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_USER: n8nuser
      DB_POSTGRESDB_PASSWORD: supersecret

      N8N_PUBLIC_API_DISABLED: true

      N8N_ENCRYPTION_KEY: mysupersecretkeythatyougenerate
      N8N_PUBLIC_API_SWAGGERUI_DISABLED: true
      N8N_RUNNERS_ENABLED: true

      # N8N_HOST: localhost
      # N8N_PORT: 5678
      # N8N_PROTOCOL: http

    depends_on:
      - postgres
    networks:
      - n8n_net

networks:
  n8n_net:
    driver: bridge
